/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "accordion": {
    name: "accordion",
    description: "A collapsible component that displays content in a vertical stack",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/accordion.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/accordion.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "alert": {
    name: "alert",
    description: "A component that displays a brief, important message to the user.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/alert.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/alert.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    description: "Displays content within a desired ratio.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/aspect-ratio.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/aspect-ratio.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "avatar": {
    name: "avatar",
    description: "A graphical representation of the user, often used in profile sections.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/avatar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/avatar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "badge": {
    name: "badge",
    description: "A small count and labeling component used to highlight a status.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "An interactive element used to trigger actions.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card": {
    name: "card",
    description: "A container component that displays content in a compact and organized way.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/card.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox": {
    name: "checkbox",
    description: "A control component that allows for multiple selections within a set.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/checkbox.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/checkbox.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input": {
    name: "input",
    description: "A field that allows user input, often used for forms or search functionality.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/input.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "label": {
    name: "label",
    description: "A text component that provides information about another component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/label.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/label.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "spinner": {
    name: "spinner",
    description: "An animated loading spinner.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/minimal/ui/spinner.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/minimal/ui/spinner.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/example/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/example/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }