/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-all.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "button-demo": {
    name: "button-demo",
    description: "An interactive element used to trigger actions.",
    type: "registry:example",
    registryDependencies: undefined,
    files: [{
      path: "registry/default/example/button-demo/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/example/button-demo/button-demo.tsx")
      const exportName = Object.keys(mod).find(
        key => typeof mod[key] === 'function' || typeof mod[key] === 'object'
      ) || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
    __style: "default"
  },
}